export const keywords = [
  "Streaming de Animes",
  "Assistir Animes Online",
  "Animes Legendados",
  "Animes Dublados",
  "Novos Animes",
  "Animes Populares",
  "Melhores Animes",
  "Animes HD",
  "Animes em Full HD",
  "Animes Grátis",
  "Animes Completos",
  "Animes com Legenda em Português",
  "Episódios de Animes",
  "Filmes de Anime",
  "Séries de Anime",
  "Lançamentos de Animes",
  "Animes de Ação",
  "Animes de Aventura",
  "Animes de Comédia",
  "Animes de Drama",
  "Animes de Fantasia",
  "Animes de Romance",
  "Animes de Terror",
  "Animes de Suspense",
  "Animes de Ficção Científica",
  "Animes Shounen",
  "Animes Shoujo",
  "Animes Seinen",
  "Animes Isekai",
  "Animes Mecha",
  "Animes de Esporte",
  "Animes Slice of Life",
  "Catálogo de Animes",
  "Animes 2024",
  "Animes Clássicos",
];
